version: 2
jobs:
  build:
    working_directory: ~/CQSCloud/common-gulp
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      NODE_ENV: test
      TZ: Africa/Johannesburg
    docker:
    - image: cimg/node:16.13.2-browsers
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-development-

    - run: npm install

    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        # This is a broad list of cache paths to include many possible development environments
        # You can probably delete some of these entries
        - vendor/bundle
        - ~/virtualenvs
        - ~/.m2
        - ~/.ivy2
        - ~/.bundle
        - ~/.go_workspace
        - ~/.gradle
        - ~/.cache/bower
        - ./node_modules

    - run: npm test

    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts

  build-master:
    working_directory: ~/CQSCloud/common-gulp
    parallelism: 1
    shell: /bin/bash --login
    environment:
      NODE_ENV: test
      TZ: Africa/Johannesburg
    docker:
    - image: cimg/node:16.13.2-browsers
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-development-

    - run: npm install

    - run: npm test

    - run: node_modules/.bin/gulp github-master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: development
      - build-master:
          filters:
            branches:
              only: development
